spring:
  profiles.include:
    - db

  servlet:
    multipart:
      enabled: true #파일 업로드 지원여부
      max-file-size: 50MB #최대 크기
      location: /Users/th/Documents/study/eb-study-templates-3week/files/ #위치
      max-request-size: 50MB #요청의 최대 크기

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    enabled: true
    cache: false # cache 사용 /사용 시 컴파일한 파일만 사용 (개발 시 미사용)
    prefix: classpath:/templates/ # 템플릿 위치 / View 파일 위치
    suffix: .html # View 파일 기본 확장자 / Controller에서 확장자를 입력하지 않아도 된다.

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # DB - MODEL 간의 네이밍 형식 변환
  type-aliases-package: com.ebtudytemplates3week.domain

